
IEXToken = ""
IEXBaseURL = "https://cloud.iexapis.com/v1"
BrokerURL = "kafka:9092"
QuoteTopic = "yogo-quotes"
HitTopic = "yogo-hits"
ScanTopic = "yogo-scans"
StatsTopic = "yogo-stats"
HttpURL = ":50100"
LogLevel = "DEBUG"