version: '2'
services:
  quoter:
    build:
      context: quoter/.
    depends_on:
      - kafka
    ports:
    - "50100:50100"
    restart: always
    command: [ "/yogo-quoter" ]
  scanner:
    build:
      context: scanner/.
    depends_on:
      - kafka
    restart: always
    command: [ "/yogo-scanner" ]


# infra
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "yogo-quotes:1:1,yogo-hits:1:1"
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock