
SocialCronSchedule = "*/5 * * * *"
WatchAPI = "http://localhost:50100"
StocktwitsAPI = "https://api.stocktwits.com"
DSN = "host=localhost user=yogo password=yogo dbname=yogo port=5432 sslmode=disable"
BrokerURL = "localhost:9092"
QuoteTopic = "yogo-stats"
SocialTopic = "yogo-social"
SentimentTopic = "yogo-sentiment"